### ISSUE TITLE
Calling Void functions through the Proxy

### ISSUE THREAD

**Issue by jerryfaust** [pipe01/RabbitRPC#1]
Hello.

We're converting a project that implemented RPC calls through .NET Remoting, to instead use RabbitMQ.  Since many of our existing RPC calls take multiple parameters, I started to devise a method to package those parameters into a single byte array (for RabbitMQ).

I then thought that I would see if someone had already solved this problem, and I found your library.  I'm very pleased with your implementation and I got a prototype working rather quickly.  Then I decided to try out your Proxy wrapper.  I like the concept very much since it allows for a very natural syntax. But I am having trouble using the proxy for function calls that return `void`.

I made sure that I had the latest packages for both **RabbitRPC** and **ClassImpl**.  Note that I also changed the project to use .NET 6.0 since the parent executable was in .NET 6.0 (and I don't know whether or not that made a difference).  But I get an exception in the **CreateProxy** call, being:
```
System.ArgumentException
  HResult=0x80070057
  Message=The type 'System.Void' may not be used as a type argument.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.ThrowIfTypeNeverValidGenericArgument(RuntimeType type)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at ClassImpl.Implementer.Member(MethodInfo method)
   at RabbitRPC.RpcCaller.CreateProxy[T]() in C:\Repos\RabbitRPC\RabbitRPC\RpcCaller.cs:line 181
    ...
    [Call Stack Truncated]

```
Am I overlooking something? or can the Proxy wrapper not be used if the interface has void methods?

Thank you for any consideration in answering this question.

Kind Regards,
Jerry.

**Comment by jerryfaust** [comment]
Follow-up: If I use v1.1.3 of ClassImpl, the CreateProxy call is successful, but I get an exception when calling a void function:
```
System.InvalidProgramException
  HResult=0x8013153A
  Message=Common Language Runtime detected an invalid program.
  Source=ProxyAssemblyID21Server
  StackTrace:
   at <>ImplID21Server.ID21Server.LoginComplete(Int32 )
   at ClientApp.FormMain.<>c__DisplayClass7_0.<buttonGet_Click>b__1() in C:\Repos\ClientApp\FormMain.cs:line 78
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    ...
    [Call Stack Truncated]

```
I can call non-void methods successfully.

**Comment by jerryfaust** [comment]
Closing issue is not-an-issue.  My misunderstanding of how to use the Calls that return no value.  Library is excellent.
